// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHashField(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['browserService']['AddHashField'](arg1, arg2, arg3, arg4, arg5);
}

export function AddListItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['browserService']['AddListItem'](arg1, arg2, arg3, arg4, arg5);
}

export function AddStreamValue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['browserService']['AddStreamValue'](arg1, arg2, arg3, arg4, arg5);
}

export function AddZSetValue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['browserService']['AddZSetValue'](arg1, arg2, arg3, arg4, arg5);
}

export function BatchSetTTL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['browserService']['BatchSetTTL'](arg1, arg2, arg3, arg4, arg5);
}

export function CleanCmdHistory() {
  return window['go']['services']['browserService']['CleanCmdHistory']();
}

export function CloseConnection(arg1) {
  return window['go']['services']['browserService']['CloseConnection'](arg1);
}

export function ConvertValue(arg1, arg2, arg3) {
  return window['go']['services']['browserService']['ConvertValue'](arg1, arg2, arg3);
}

export function DeleteKey(arg1, arg2, arg3, arg4) {
  return window['go']['services']['browserService']['DeleteKey'](arg1, arg2, arg3, arg4);
}

export function DeleteKeys(arg1, arg2, arg3, arg4) {
  return window['go']['services']['browserService']['DeleteKeys'](arg1, arg2, arg3, arg4);
}

export function DeleteOneKey(arg1, arg2, arg3) {
  return window['go']['services']['browserService']['DeleteOneKey'](arg1, arg2, arg3);
}

export function ExportKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['browserService']['ExportKey'](arg1, arg2, arg3, arg4, arg5);
}

export function FlushDB(arg1, arg2, arg3) {
  return window['go']['services']['browserService']['FlushDB'](arg1, arg2, arg3);
}

export function GetClientList(arg1) {
  return window['go']['services']['browserService']['GetClientList'](arg1);
}

export function GetCmdHistory(arg1, arg2) {
  return window['go']['services']['browserService']['GetCmdHistory'](arg1, arg2);
}

export function GetKeyDetail(arg1) {
  return window['go']['services']['browserService']['GetKeyDetail'](arg1);
}

export function GetKeySummary(arg1) {
  return window['go']['services']['browserService']['GetKeySummary'](arg1);
}

export function GetKeyType(arg1) {
  return window['go']['services']['browserService']['GetKeyType'](arg1);
}

export function GetSlowLogs(arg1, arg2) {
  return window['go']['services']['browserService']['GetSlowLogs'](arg1, arg2);
}

export function ImportCSV(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['browserService']['ImportCSV'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadAllKeys(arg1, arg2, arg3, arg4) {
  return window['go']['services']['browserService']['LoadAllKeys'](arg1, arg2, arg3, arg4);
}

export function LoadNextAllKeys(arg1, arg2, arg3, arg4) {
  return window['go']['services']['browserService']['LoadNextAllKeys'](arg1, arg2, arg3, arg4);
}

export function LoadNextKeys(arg1, arg2, arg3, arg4) {
  return window['go']['services']['browserService']['LoadNextKeys'](arg1, arg2, arg3, arg4);
}

export function OpenConnection(arg1) {
  return window['go']['services']['browserService']['OpenConnection'](arg1);
}

export function OpenDatabase(arg1, arg2) {
  return window['go']['services']['browserService']['OpenDatabase'](arg1, arg2);
}

export function RemoveStreamValues(arg1, arg2, arg3, arg4) {
  return window['go']['services']['browserService']['RemoveStreamValues'](arg1, arg2, arg3, arg4);
}

export function RenameKey(arg1, arg2, arg3, arg4) {
  return window['go']['services']['browserService']['RenameKey'](arg1, arg2, arg3, arg4);
}

export function ServerInfo(arg1) {
  return window['go']['services']['browserService']['ServerInfo'](arg1);
}

export function SetHashValue(arg1) {
  return window['go']['services']['browserService']['SetHashValue'](arg1);
}

export function SetKeyTTL(arg1, arg2, arg3, arg4) {
  return window['go']['services']['browserService']['SetKeyTTL'](arg1, arg2, arg3, arg4);
}

export function SetKeyValue(arg1) {
  return window['go']['services']['browserService']['SetKeyValue'](arg1);
}

export function SetListItem(arg1) {
  return window['go']['services']['browserService']['SetListItem'](arg1);
}

export function SetSetItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['browserService']['SetSetItem'](arg1, arg2, arg3, arg4, arg5);
}

export function Start(arg1) {
  return window['go']['services']['browserService']['Start'](arg1);
}

export function Stop() {
  return window['go']['services']['browserService']['Stop']();
}

export function UpdateSetItem(arg1) {
  return window['go']['services']['browserService']['UpdateSetItem'](arg1);
}

export function UpdateZSetValue(arg1) {
  return window['go']['services']['browserService']['UpdateZSetValue'](arg1);
}
