// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAll() {
  return window['go']['services']['cliService']['CloseAll']();
}

export function CloseCli(arg1) {
  return window['go']['services']['cliService']['CloseCli'](arg1);
}

export function Start(arg1) {
  return window['go']['services']['cliService']['Start'](arg1);
}

export function StartCli(arg1, arg2) {
  return window['go']['services']['cliService']['StartCli'](arg1, arg2);
}
