// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CloseAll():Promise<void>;

export function CloseCli(arg1:string):Promise<types.JSResp>;

export function Start(arg1:context.Context):Promise<void>;

export function StartCli(arg1:string,arg2:number):Promise<types.JSResp>;
