// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroup(arg1) {
  return window['go']['services']['connectionService']['CreateGroup'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['services']['connectionService']['DeleteConnection'](arg1);
}

export function DeleteGroup(arg1, arg2) {
  return window['go']['services']['connectionService']['DeleteGroup'](arg1, arg2);
}

export function ExportConnections() {
  return window['go']['services']['connectionService']['ExportConnections']();
}

export function GetConnection(arg1) {
  return window['go']['services']['connectionService']['GetConnection'](arg1);
}

export function ImportConnections() {
  return window['go']['services']['connectionService']['ImportConnections']();
}

export function ListConnection() {
  return window['go']['services']['connectionService']['ListConnection']();
}

export function ListSentinelMasters(arg1) {
  return window['go']['services']['connectionService']['ListSentinelMasters'](arg1);
}

export function ParseConnectURL(arg1) {
  return window['go']['services']['connectionService']['ParseConnectURL'](arg1);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['services']['connectionService']['RenameGroup'](arg1, arg2);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['services']['connectionService']['SaveConnection'](arg1, arg2);
}

export function SaveLastDB(arg1, arg2) {
  return window['go']['services']['connectionService']['SaveLastDB'](arg1, arg2);
}

export function SaveRefreshInterval(arg1, arg2) {
  return window['go']['services']['connectionService']['SaveRefreshInterval'](arg1, arg2);
}

export function SaveSortedConnection(arg1) {
  return window['go']['services']['connectionService']['SaveSortedConnection'](arg1);
}

export function Start(arg1) {
  return window['go']['services']['connectionService']['Start'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['services']['connectionService']['TestConnection'](arg1);
}
