// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function ExportLog(arg1:Array<string>):Promise<types.JSResp>;

export function Start(arg1:context.Context):Promise<void>;

export function StartMonitor(arg1:string):Promise<types.JSResp>;

export function StopAll():Promise<void>;

export function StopMonitor(arg1:string):Promise<types.JSResp>;
