// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportLog(arg1) {
  return window['go']['services']['monitorService']['ExportLog'](arg1);
}

export function Start(arg1) {
  return window['go']['services']['monitorService']['Start'](arg1);
}

export function StartMonitor(arg1) {
  return window['go']['services']['monitorService']['StartMonitor'](arg1);
}

export function StopAll() {
  return window['go']['services']['monitorService']['StopAll']();
}

export function StopMonitor(arg1) {
  return window['go']['services']['monitorService']['StopMonitor'](arg1);
}
