// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function Publish(arg1:string,arg2:string,arg3:string):Promise<types.JSResp>;

export function Start(arg1:context.Context):Promise<void>;

export function StartSubscribe(arg1:string):Promise<types.JSResp>;

export function StopAll():Promise<void>;

export function StopSubscribe(arg1:string):Promise<types.JSResp>;
