// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Publish(arg1, arg2, arg3) {
  return window['go']['services']['pubsubService']['Publish'](arg1, arg2, arg3);
}

export function Start(arg1) {
  return window['go']['services']['pubsubService']['Start'](arg1);
}

export function StartSubscribe(arg1) {
  return window['go']['services']['pubsubService']['StartSubscribe'](arg1);
}

export function StopAll() {
  return window['go']['services']['pubsubService']['StopAll']();
}

export function StopSubscribe(arg1) {
  return window['go']['services']['pubsubService']['StopSubscribe'](arg1);
}
