// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function Info():Promise<types.JSResp>;

export function SaveFile(arg1:string,arg2:string,arg3:Array<string>):Promise<types.JSResp>;

export function SelectFile(arg1:string,arg2:Array<string>):Promise<types.JSResp>;

export function Start(arg1:context.Context,arg2:string):Promise<void>;
