// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Info() {
  return window['go']['services']['systemService']['Info']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['services']['systemService']['SaveFile'](arg1, arg2, arg3);
}

export function SelectFile(arg1, arg2) {
  return window['go']['services']['systemService']['SelectFile'](arg1, arg2);
}

export function Start(arg1, arg2) {
  return window['go']['services']['systemService']['Start'](arg1, arg2);
}
